security:
    providers:
        chain_provider:
            chain:
                providers: [in_memory, users]
        users:
            entity: { class: AppBundle\Entity\User, property: username }
        in_memory:
            memory:
                users:
                    klipa:
                        password: klipaklipa
                        roles: 'ROLE_ADMIN'
    encoders:
        AppBundle\Entity\User:
            algorithm: md5
        Symfony\Component\Security\Core\User\User:
            algorithm: plaintext
    firewalls:
        secured_area_mod:
            pattern:    /app
            anonymous: ~
            form_login:
                login_path:  login
                check_path:  login_check
                default_target_path: logged_in
                always_use_default_target_path: true
                provider: chain_provider
            logout:
                path:   logout
                target: login
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/app, roles: ROLE_USER }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
